#!/bin/bash 
# Array of files to copy
files=( "./src/uml-sprinkler*" "README.md")

# Create the dist directory if it doesn't exist
mkdir -p dist


# copy the files using single cp command without using loop for cp command

# print the example of cp command looks like in the above scenario
cp ${files[@]} dist/ && echo "Files copied successfully" || echo "Files not copied successfully" 

cp package-build.json dist/package.json && echo "Files copied successfully" || echo "Files not copied successfully" 


exit 0